name: Test mimetype against UNIX file(1)
on:
  workflow_dispatch:
    inputs:
      version1:
        description: 'What mimetype version to test initially'
        default: 'github.com/gabriel-vasile/mimetype@master'
      version2:
        description: |
          What mimetype version to compare with;
          forks can be used too, ex: github.com/username/mimetype@commitSHA
        default: ''
        required: true
env:
  CI: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout file
      uses: actions/checkout@v4.2.2
      with:
        repository: file/file
        path: file
    - name: Build file
      run: |
        cd file
        which file
        file --version
        autoreconf -f -i
        ./configure --disable-silent-rules
        make -j4
        make install
        which file
        file --version
        file --mime ./*
