name: Test mimetype against UNIX file(1)
on:
  workflow_dispatch:
    inputs:
      commit:
        description: 'What commit of mimetype to test with. By default uses latest release.'
        default: ''

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version-file: 'go.mod'
    - name: Install mimetype latest release
      if: ${{ github.event.inputs.commit == '' }}
      run: go get -u github.com/gabriel-vasile/mimetype
    - name: Install mimetype from commit
      if: ${{ github.event.inputs.commit != '' }}
      run: go get -u "github.com/gabriel-vasile/mimetype@${{ github.event.inputs.commit }}"
    - name: Test
      run: |
        go run zipshuffler.go
        go run truncate.go
        DEBUG=1 go run main.go
