name: Test mimetype against UNIX file(1)
on:
  workflow_dispatch:
    inputs:
      version1:
        description: 'What mimetype version to test initially'
        default: 'github.com/gabriel-vasile/mimetype@master'
      version2:
        description: |
          What mimetype version to compare with;
          forks can be used too, ex: github.com/username/mimetype@commitSHA
        default: ''
        required: true
env:
  CI: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout file
      uses: actions/checkout@v4.2.2
      with:
        repository: file/file
        path: file
    - name: Build file
      run: |
        cd file
        which file
        file --version
        ./configure --disable-silent-rules
        make -j4
        make install
        which file
        file --version
    - name: Checkout code
      uses: actions/checkout@v4.2.2
    - name: Install Go
      uses: actions/setup-go@v5.4.0
      with:
        go-version-file: 'go.mod'
    - name: Generate extra files
      run: |
        go run zipshuffler.go
        go run truncate.go
    - name: Initial run
      run: |
        go mod edit -replace="github.com/gabriel-vasile/mimetype=${{ github.event.inputs.version1 }}"
        go mod tidy
        go run main.go > version1
    - name: Second run
      run: |
        go mod edit -replace="github.com/gabriel-vasile/mimetype=${{ github.event.inputs.version2 }}"
        go mod tidy
        go run main.go > version2
    - name: Compare results
      run: diff --color=always version1 version2 || true
